
project_id = "zzijiecsvyzaqedatuip"

[functions.sefaz-api-proxy]
timeout_s = 55
memory_mb = 256
verify_jwt = false

[functions.update-tracked-prices]
timeout_s = 300
memory_mb = 1024
verify_jwt = false
